#!/bin/bash
# Attach the EBS volume

# Get a random device letter, we will hang forever if we try to attach a volume to an already mapped device.
for device_letter in {f..z}; do
	device_path="/dev/xvd$device_letter"
	[ ! -b $device_path ] && break
done
[ -b $device_path ] && die "No free device letters found (tried sdf to sdz)!"

attachment_status=`ec2-attach-volume "$volume_id" \
	--instance "$instance_id" --device "$device" | grep 'attached' || true`
# Wait until the volume is attached
dotdot "$attachment_status" "ec2dvol $volume_id -F 'attachment.status=attached' || true"
